name: Restrict PRs to Community Folders
on:
  pull_request:
    paths:
        - 'Scripts/Community Extensions/**'
        - 'Scripts/Community Templates/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Allow only community folders
        run: echo "Pull-Request doesn't affect main files ✅"